- hosts: web
  user: root
  tasks:
  - name: mkdir
    file: path={{ item.path }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} state=directory
    with_items:
      - {"path":"/opt/ansible", "owner":"root", "group":"root", "mode":"0755"}